import type { Metadata, Viewport } from "next";
import { Inter } from "next/font/google";
import type { ReactNode } from "react";
import "./globals.scss";
import { MainHeader } from "@/shared/components/layout/MainHeader/MainHeader";
import { ClientWrapper } from "@/shared/components/layout/ClientWrapper/ClientWrapper";

const inter = Inter({ subsets: ["latin"] });

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 5,
};

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ClientWrapper>
          <a href="#main-content" className="skip-to-main">
            Skip to main content
          </a>
          <MainHeader />
          <main id="main-content">
            {children}
          </main>
        </ClientWrapper>
      </body>
    </html>
  );
}
